#!/usr/bin/env bash
redirect301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $redirect301" /etc/nginx/sites-available/default
sudo service nginx restart